user						nobody;

worker_processes			1;

error_log					../log/error.log warn;

# This is where config files that affect the root context should go.
include						conf.d/*.conf;

events {
	worker_connections		1024;
}

http {
	include					mime/types.conf;
	default_type			application/octet-stream;

	client_max_body_size	1m;

	access_log				../log/access.log;

	# Server config files should go in sites-available. To enable a server,
	# create a symlink in sites-enabled from its config file in sites-available.
	include					sites-enabled/*.conf;
}
