#!/usr/bin/env bash

shopt -s globstar
shopt -s nullglob
exec < /dev/tty

read -n 1 -p "Check for remaining TODO comments? [y/n] " ANSWER
echo
if [[ $ANSWER == "y" ]]; then
	grep -H -n TODO -- ./**/Makefile ./src/**/*.{c,h,t}pp ./main/**/*.cpp \
		|| echo "No TODO comments found!"
fi
echo

read -n 1 -p "Run clang-format? [y/n] " ANSWER
echo
if [[ $ANSWER == "y" ]]; then
    clang-format -i -- ./src/**/*.{c,h,t}pp ./main/**/*.cpp
fi
echo

read -n 1 -p "Run clang-tidy? [y/n] " ANSWER
echo
if [[ $ANSWER == "y" ]]; then
	INCLUDES="$(find ./src -type d | sed s/^/-I/ | xargs)"
	clang-tidy ./src/**/*.{c,h,t}pp ./main/**/*.cpp -- \
		-x c++ -D IGNORE_TPP_WRAPPERS $INCLUDES
fi
echo

read -n 1 -p "Check compilation? [y/n] " ANSWER
echo
if [[ $ANSWER == "y" ]]; then
	make re
fi
echo

read -n 1 -p "Run tests? [y/n] " ANSWER
echo
if [[ $ANSWER == "y" ]]; then
    make test-all
fi
echo

read -n 1 -p "Run tests with Valgrind? [y/n] " ANSWER
echo
if [[ $ANSWER == "y" ]]; then
    make valgrind-all
fi
