POST /upload HTTP/1.1
Host: example.com
Transfer-Encoding: chunked
X-Header-0: value
X-Header-1: value
X-Header-2: value
X-Header-3: value
X-Header-4: value
X-Header-5: value
X-Header-6: value
X-Header-7: value
X-Header-8: value
X-Header-9: value
X-Header-10: value
X-Header-11: value
X-Header-12: value
X-Header-13: value
X-Header-14: value
X-Header-15: value
X-Header-16: value
X-Header-17: value
X-Header-18: value
X-Header-19: value
X-Header-20: value
X-Header-21: value
X-Header-22: value
X-Header-23: value
X-Header-24: value
X-Header-25: value
X-Header-26: value
X-Header-27: value
X-Header-28: value
X-Header-29: value
X-Header-30: value
X-Header-31: value
X-Header-32: value
X-Header-33: value
X-Header-34: value
X-Header-35: value
X-Header-36: value
X-Header-37: value
X-Header-38: value
X-Header-39: value
X-Header-40: value
X-Header-41: value
X-Header-42: value
X-Header-43: value
X-Header-44: value
X-Header-45: value
X-Header-46: value
X-Header-47: value
X-Header-48: value
X-Header-49: value
X-Header-50: value
X-Header-51: value
X-Header-52: value
X-Header-53: value
X-Header-54: value
X-Header-55: value
X-Header-56: value
X-Header-57: value
X-Header-58: value
X-Header-59: value

0
X-Trailer-0: value
X-Trailer-1: value
X-Trailer-2: value
X-Trailer-3: value
X-Trailer-4: value
X-Trailer-5: value
X-Trailer-6: value
X-Trailer-7: value
X-Trailer-8: value
X-Trailer-9: value
X-Trailer-10: value
X-Trailer-11: value
X-Trailer-12: value
X-Trailer-13: value
X-Trailer-14: value
X-Trailer-15: value
X-Trailer-16: value
X-Trailer-17: value
X-Trailer-18: value
X-Trailer-19: value
X-Trailer-20: value
X-Trailer-21: value
X-Trailer-22: value
X-Trailer-23: value
X-Trailer-24: value
X-Trailer-25: value
X-Trailer-26: value
X-Trailer-27: value
X-Trailer-28: value
X-Trailer-29: value
X-Trailer-30: value
X-Trailer-31: value
X-Trailer-32: value
X-Trailer-33: value
X-Trailer-34: value
X-Trailer-35: value
X-Trailer-36: value
X-Trailer-37: value
X-Trailer-38: value
X-Trailer-39: value
X-Trailer-40: value
X-Trailer-41: value
X-Trailer-42: value
X-Trailer-43: value
X-Trailer-44: value
X-Trailer-45: value
X-Trailer-46: value
X-Trailer-47: value
X-Trailer-48: value
X-Trailer-49: value
X-Trailer-50: value
X-Trailer-51: value
X-Trailer-52: value
X-Trailer-53: value
X-Trailer-54: value
X-Trailer-55: value
X-Trailer-56: value
X-Trailer-57: value
X-Trailer-58: value
X-Trailer-59: value

