#!/usr/bin/env python3
# cgi-bin/greet.py — handles GET /cgi-bin/greet.py?name=...
# Reads QUERY_STRING, parses it, returns an HTML page (not plain text)
# so it renders nicely when linked from the demo site.
import os
from urllib.parse import parse_qs
from html import escape

query = os.environ.get("QUERY_STRING", "")
params = parse_qs(query)
name = params.get("name", ["stranger"])[0]
name = escape(name)  # never trust user input straight into HTML

print("Content-Type: text/html")
print()
print(f"""<!DOCTYPE html>
<html>
<head><title>Greeting</title><link rel="stylesheet" href="/style.css"></head>
<body>
  <main><section class="card">
    <h2>Hello, {name}!</h2>
    <p>This page was generated by <code>cgi-bin/greet.py</code> from a GET request.</p>
    <p><a href="/" style="color:#5fb3ff">&larr; back</a></p>
  </section></main>
</body>
</html>""")
