#!/usr/bin/env python3
# cgi-bin/guestbook.py — handles POST /cgi-bin/guestbook.py
# Reads CONTENT_LENGTH bytes from stdin (the form body), parses it as
# application/x-www-form-urlencoded (what a normal HTML <form> sends),
# appends it to a small local file so repeated submissions accumulate,
# and returns an HTML page listing all entries so far.
import os
import sys
from urllib.parse import parse_qs
from html import escape

length = int(os.environ.get("CONTENT_LENGTH", "0"))
body = sys.stdin.read(length) if length > 0 else ""
params = parse_qs(body)
author = escape(params.get("author", [""])[0])
message = escape(params.get("message", [""])[0])

# Store entries next to this script so it works regardless of CWD.
entries_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), "guestbook.txt")

if author and message:
    with open(entries_path, "a") as f:
        f.write(f"{author}|{message}\n")

rows = ""
if os.path.exists(entries_path):
    with open(entries_path) as f:
        for line in f:
            a, _, m = line.strip().partition("|")
            rows += f"<li><strong>{escape(a)}:</strong> {escape(m)}</li>"

print("Content-Type: text/html")
print()
print(f"""<!DOCTYPE html>
<html>
<head><title>Guestbook</title><link rel="stylesheet" href="/style.css"></head>
<body>
  <main><section class="card">
    <h2>Thanks, {author or "anonymous"}!</h2>
    <p>This page was generated by <code>cgi-bin/guestbook.py</code> from a POST request.</p>
    <h3>Guestbook so far:</h3>
    <ul>{rows or "<li>No entries yet.</li>"}</ul>
    <p><a href="/" style="color:#5fb3ff">&larr; back</a></p>
  </section></main>
</body>
</html>""")
